options:
  prometheus_client_listen_port:
    type: int
    default: 9103
    description: The port on which telegraf is scraped by prometheus clients
  disable_nvidia_smi:
    type: boolean
    default: false
    description: "Disable nvidia-smi for harvesting GPU metrics"
# TODO:
#  listen_ip_range:
#    type: string
#    default: ""
#    description: Space separated string of ip-networks for which to telegraf listens to.