#!/bin/bash
# config-changed occurs everytime a new configuration value is updated (juju set)

source ./lib/utils

# Render ...
render_telegraf
systemctl restart telegraf

# Clear previously opened ports
for p in $(opened-ports | awk -F/ '{print $1}'); do
  close-port $p/tcp
done

# Announce altered ports
prometheus_client_listen_port=$(config-get prometheus_client_listen_port)
open-port $prometheus_client_listen_port/tcp

# Set status
status-set active "Monitoring ${JUJU_PRINCIPAL_UNIT}"

